export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_ACTIVATE = 'AUTH_ACTIVATE';
export const AUTH_ACTIVATE_SUCCESS = 'AUTH_ACTIVATE_SUCCESS';
export const AUTH_ACTIVATE_FAIL = 'AUTH_ACTIVATE_FAIL';
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING';
export const AUTH_SET_MESSAGE = 'AUTH_SET_MESSAGE';
export const AUTH_CLEAR_MESSAGE = 'AUTH_CLEAR_MESSAGE';

export const ERROR_SET = 'ERROR_SET';
export const ERROR_CLEAR = 'ERROR_CLEAR';

export const USER_SET = 'USER_SET';
export const USER_CLEAR = 'USER_CLEAR';

export const UPDATE_ADD_MESSAGE = 'UPDATE_ADD_MESSAGE';
export const UPDATE_REMOVE_MESSAGE = 'UPDATE_REMOVE_MESSAGE';
export const UPDATE_CLEAR_MESSAGES = 'UPDATE_CLEAR_MESSAGES';

export const GROUP_SET_ACTIVE_ID = 'GROUP_SET_ACTIVE_ID';
export const GROUP_SET_ALL = 'GROUP_SET_ALL';
export const GROUP_ADD = 'GROUP_ADD';
export const GROUP_REMOVE = 'GROUP_REMOVE';
export const GROUP_CHANGING = 'GROUP_CHANGING';
export const GROUP_LOADING = 'GROUP_LOADING';

export const ALL_CLEAR = 'ALL_CLEAR';